### ISSUE TITLE
not able to put book in grindstone

### ISSUE THREAD

**Issue by Cole9290** [mschae23/grind-enchantments#27] opened 2022-06-12 11:28 UTC
i dont know if i missed something but following the curseforge page i did everything right...

**Comment by mschae23** [comment] 2022-06-13 14:00
Is the mod installed on the server?

**Comment by Cole9290** [comment] 2022-06-14 17:23
I dunno, it’s a solo world without any others. I guess that is on server right or is there another mods folder I don’t know about?

**Comment by mschae23** [comment] 2022-06-15 14:06
Okay, if it is in a singleplayer world, the distinction between client and server doesn't matter. Unfortunately, I can't reproduce this myself, so I don't really know what the problem could be.

**Comment by mschae23** [comment] 2023-01-08 19:47
I'm closing this issue now, because I cannot reproduce it.
Feel free to open another one with more information if this is still happening.

**Closed by mschae23** 2023-01-08 19:47 UTC
Labels: bug
